server:
  port: 8005
spring:
  application:
    name: mango-consumer
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1 #样本采集，默认为0.1
  boot:
    admin:
      client:
        url: "localhost:8000"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enbale: true
hello: hello,dev configurations
